steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'deploy-cf'
      apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com' # for example, "https://api.cf.eu10.hana.ondemand.com"
      org: '7b45cd19trial'
      space: 'dev1'
